### ISSUE TITLE
Dead links in the 'Read Me'

### ISSUE THREAD

**Issue by seajane** [FredHutch/VISCfunctions#60]
**Issue:** 
The first two links in the "Read Me" for VISC Functions no longer redirect the user to any working pages.

**Example or Reproducible Case:**
When clicking on either of the two links below, the user is directed to a "404" page.
![image](https://user-images.githubusercontent.com/8787869/92525960-93515680-f1d9-11ea-8d04-f35ea86e3530.png)

**Link:**
https://github.com/FredHutch/VISCfunctions

**Comment by wfulp** [comment]
links no longer appear after #51
