### ISSUE TITLE
Remove `do()` from examples

### ISSUE THREAD

**Issue by monicagerber** [FredHutch/VISCfunctions#8]
We are being encouraged to move away from `do()`, so we should think about using different examples in VISCfunctions (and analysis/processing code). See this [community post](https://community.rstudio.com/t/should-i-move-away-from-do-and-rowwise/2857/13) and [pull request](https://github.com/tidyverse/tidyr/pull/434).

One alternative uses a new function called `group_map()`:
```
group_testing_tibble <- exampleData_BAMA %>%
  group_by(antigen, visitno) %>%
  group_map(
    ~VISCfunctions::pairwise_test_cont(
      x = .$magnitude, group = .$group, paired = FALSE, method = 'wilcox', 
      alternative = "less", num_needed_for_test = 3, verbose = TRUE
      )
    )
```
instead of:
```
group_testing_tibble <- exampleData_BAMA %>%
  group_by(antigen, visitno) %>%
  do(pairwise_test_cont(x = .$magnitude, group = .$group, 
                        paired = FALSE, method = 'wilcox',
                        alternative = "less", digits = 3, 
                        num_needed_for_test = 3, verbose = TRUE))
```

**Comment by seajane** [comment]
Replaced all examples of `do` with `group_by` and `summarise` from `dplyr`
https://github.com/FredHutch/VISCfunctions/pull/65/commits/9da86710b94c102d21ccbb8b6339dcc2f96deb24
