### ISSUE TITLE
Missing pracma package dependency?

### ISSUE THREAD

**Issue by kelliemac** [FredHutch/VISCfunctions#88]
I get the following error when running
`remotes::install_github("FredHutch/VISCfunctions", build_vignettes = TRUE)`

```
Quitting from lines 297-311 [unnamed-chunk-10] (Overview.Rmd)
   Error: processing vignette 'Overview.Rmd' failed with diagnostics:
   there is no package called 'pracma'
   --- failed re-building ‘Overview.Rmd’
```

Appears to be related to a missing package dependency. When I run `install.packages('pracma')` and then try again, everything works.

**Comment by slager** [comment]
You will need to install the 'Suggests' packages to build the vignettes, which is in line with best practices for DESCRIPTION files.

The default argument `dependencies = NA` for `remotes::install_github()` does not install suggested packages.

This should work:

```
remotes::install_github("FredHutch/VISCfunctions", dependencies = TRUE, build_vignettes = TRUE)
```

I don't think there's a problem here unless we want to update the install instructions. The current error message at least gives a good clue as to how to solve it like you pointed out.

**Comment by kelliemac** [comment]
thanks Dave! I think we should update the installation instructions in the readme. but not urgent.
