### ISSUE TITLE
GitHub Actions CI for VISCfunctions needs to be refreshed

### ISSUE THREAD

**Issue by slager** [FredHutch/VISCfunctions#90]

**Comment by kelliemac** [comment]
@slager ok to close this issue?

**Comment by slager** [comment]
I was going to close it once I saw that the codecov runner was working after merging to main, but probably also fine to close now since at least the R CMD checks are working

**Comment by slager** [comment]
Will just close it for now.  Can re-open if the codecov stuff doesn't work in the next new PR!
